// lib/link-map.ts
export const LINK_MAP = {
  hochwassercheck: { href: "/#hochwasser-check" },
  starkregen: { href: "https://www.berlin.de/sen/uvk/umwelt/wasser-und-geologie/starkregen-und-ueberflutungen/gefahren/", target: "_blank" },
  risikokarten: { href: "https://www.berlin.de/sen/uvk/umwelt/wasser-und-geologie/hochwasser/hochwasserrisikomanagementrichtlinie/#risikokarten", target: "_blank" },
  gdv: { href: "https://www.gdv.de/gdv/statistik/datenservice-zum-naturgefahrenreport/sachversicherung-elementar", target: "_blank", variant: "extern" },
  hochwasserzentralen: { href: "https://www.hochwasserzentralen.de/", target: "_blank", variant: "extern" },
  naturgefahrenportal: { href: "https://www.naturgefahrenportal.de/de", target: "_blank", variant: "extern" },
  warntag: { href: "https://www.berlin.de/katastrophenschutz/warnung-und-information/warnung-und-information-der-bevoelkerung/artikel.1588862.php", target: "_blank" },
  bevoelkerungswarnung: { href: "https://www.berlin.de/katastrophenschutz/warnung-und-information/warnung-und-information-der-bevoelkerung/warnung-und-information-der-bevoelkerung-in-gefahrenlagen-1273411.php#berlin", target: "_blank" },
  nina: { href: "https://www.bbk.bund.de/DE/Warnung-Vorsorge/Warn-App-NINA/warn-app-nina_node.html", target: "_blank", variant: "extern" },
  warnwetter: { href: "https://www.dwd.de/DE/service/dwd-apps/dwdapps_node.html", target: "_blank", variant: "extern" },
  dwd: { href: "https://www.dwd.de/DE/wetter/warnungen_aktuell/kriterien/warnstufen.html", target: "_blank", variant: "extern" },
  sirenen: { href: "https://www.berlin.de/katastrophenschutz/warnung-und-information/sirenen/artikel.1578804.php#headline_1_39", target: "_blank" },
  leuchttuerme: { href: "https://www.berlin.de/katastrophenschutz/warnung-und-information/anlaufstellen-fuer-die-bevoelkerung/", target: "_blank" },
  notfallplan: { href: "https://www.bbk.bund.de/SharedDocs/Downloads/DE/Mediathek/Publikationen/Buergerinformationen/Ratgeber/BBK-Vorsorgen-fuer-Krisen-und-Katastrophen.pdf?__blob=publicationFile&v=41", target: "_blank", variant: "extern" },
  notfallrucksack: { href: "https://www.bbk.bund.de/SharedDocs/Downloads/DE/Mediathek/Publikationen/Buergerinformationen/Ratgeber/BBK-Vorsorgen-fuer-Krisen-und-Katastrophen.pdf?__blob=publicationFile&v=41", target: "_blank", variant: "extern" },
  kurbelradio: { href: "https://www.bbk.bund.de/SharedDocs/Downloads/DE/Mediathek/Publikationen/Buergerinformationen/Ratgeber/BBK-Vorsorgen-fuer-Krisen-und-Katastrophen.pdf?__blob=publicationFile&v=41", target: "_blank", variant: "extern" },
  hochwasserpass: { href: "https://www.hochwasser-pass.info/", target: "_blank", variant: "extern" },
  fib: { href: "https://www.fib-bund.de/inhalt/themen/hochwasser/", target: "_blank", variant: "extern" },
  smartwater: { href: "https://gemeinsamdigital.berlin.de/de/smart-water/", target: "_blank", variant: "extern" },
  elementarversicherung: { href: "https://www.gdv.de/gdv/statistik/datenservice-zum-naturgefahrenreport/sachversicherung-elementar", target: "_blank", variant: "extern" },
  fibhochwasser: { href: "https://www.fib-bund.de/inhalt/themen/hochwasser/", target: "_blank", variant: "extern" },
} satisfies Record<string, { href: string; target?: string; variant?: string }>;