// lib/link-map.ts
export const LINK_MAP = {
  hochwassercheck: { href: "/#hochwasser-check" },
  handlungsempfehlungen: { href: "/handlungsempfehlungen" },
  anker4: { href: "#anker4" },
  anker3: { href: "/hintergrund-informationen#anker3" },
  starkregen: { href: "https://www.berlin.de/sen/uvk/umwelt/wasser-und-geologie/starkregen-und-ueberflutungen/gefahren/", target: "_blank" },
  risikokarten: { href: "https://www.berlin.de/sen/uvk/umwelt/wasser-und-geologie/hochwasser/hochwasserrisikomanagementrichtlinie/#risikokarten", target: "_blank" },
  gdv: { href: "https://www.gdv.de/gdv/statistik/datenservice-zum-naturgefahrenreport/sachversicherung-elementar", target: "_blank", variant: "extern" },
  hochwasserzentralen: { href: "https://www.hochwasserzentralen.de/", target: "_blank", variant: "extern" },
  naturgefahrenportal: { href: "https://www.naturgefahrenportal.de/de", target: "_blank", variant: "extern" },
  warntag: { href: "https://www.berlin.de/katastrophenschutz/warnung-und-information/warnung-und-information-der-bevoelkerung/artikel.1588862.php", target: "_blank" },
  bevoelkerungswarnung: { href: "https://www.berlin.de/katastrophenschutz/warnung-und-information/warnung-und-information-der-bevoelkerung/warnung-und-information-der-bevoelkerung-in-gefahrenlagen-1273411.php#berlin", target: "_blank" },
  nina: { href: "https://www.bbk.bund.de/DE/Warnung-Vorsorge/Warn-App-NINA/warn-app-nina_node.html", target: "_blank", variant: "extern" },
  warnwetter: { href: "https://www.dwd.de/DE/service/dwd-apps/dwdapps_node.html", target: "_blank", variant: "extern" },
  dwd: { href: "https://www.dwd.de/DE/wetter/warnungen_aktuell/kriterien/warnstufen.html", target: "_blank", variant: "extern" },
  sirenen: { href: "https://www.berlin.de/katastrophenschutz/warnung-und-information/sirenen/artikel.1578804.php#headline_1_39", target: "_blank" },
  leuchttuerme: { href: "https://www.berlin.de/katastrophenschutz/warnung-und-information/anlaufstellen-fuer-die-bevoelkerung/", target: "_blank" },
  notfallplan: { href: "https://www.bbk.bund.de/SharedDocs/Downloads/DE/Mediathek/Publikationen/Buergerinformationen/Ratgeber/BBK-Vorsorgen-fuer-Krisen-und-Katastrophen.pdf?__blob=publicationFile&v=41", target: "_blank", variant: "extern" },
  notfallrucksack: { href: "https://www.bbk.bund.de/SharedDocs/Downloads/DE/Mediathek/Publikationen/Buergerinformationen/Ratgeber/BBK-Vorsorgen-fuer-Krisen-und-Katastrophen.pdf?__blob=publicationFile&v=41", target: "_blank", variant: "extern" },
  kurbelradio: { href: "https://www.bbk.bund.de/SharedDocs/Downloads/DE/Mediathek/Publikationen/Buergerinformationen/Ratgeber/BBK-Vorsorgen-fuer-Krisen-und-Katastrophen.pdf?__blob=publicationFile&v=41", target: "_blank", variant: "extern" },
  hochwasserpass: { href: "https://www.hochwasser-pass.info/", target: "_blank", variant: "extern" },
  fib: { href: "https://www.fib-bund.de/inhalt/themen/hochwasser/", target: "_blank", variant: "extern" },
  smartwater: { href: "https://gemeinsamdigital.berlin.de/de/smart-water/", target: "_blank", variant: "extern" },
  elementarversicherung: { href: "https://www.gdv.de/gdv/statistik/datenservice-zum-naturgefahrenreport/sachversicherung-elementar", target: "_blank", variant: "extern" },
  fibhochwasser: { href: "https://www.fib-bund.de/inhalt/themen/hochwasser/", target: "_blank", variant: "extern" },
  wasserportal: { href: "https://wasserportal.berlin.de/warnungen.php", target: "_blank" },
  aquaplaning: { href: "https://www.adac.de/rund-ums-fahrzeug/ausstattung-technik-zubehoer/reifen/sicherheit/aquaplaning/", target: "_blank", variant: "extern" },
  dvgwtrinkwasser: { href: "https://www.dvgw.de/medien/dvgw/leistungen/publikationen/Info-wiederinbetriebnahme-trinkwasser-installation-nach-betriebsunterbrechungen.pdf", target: "_blank", variant: "extern" },
  gdvstarkregen: { href: "https://www.gdv.de/gdv/themen/klima/128-millionen-euro-starkregen-schaden-in-berlin-52782", target: "_blank", variant: "extern" },
  dwdthemadestages: { href: "https://www.dwd.de/DE/wetter/thema_des_tages/2025/9/28.html", target: "_blank", variant: "extern" },
  umweltatlas: { href: "https://www.berlin.de/umweltatlas/wasser/starkregen/fortlaufend-aktualisiert/zusammenfassung/", target: "_blank" },
  gdviewer: { href: "https://gdi.berlin.de/viewer/main/", target: "_blank", variant: "extern" },
  regenwasseragentur: { href: "https://regenwasseragentur.berlin/schwammstadt/", target: "_blank", variant: "extern" },
  whg: { href: "https://www.gesetze-im-internet.de/whg_2009/__5.html", target: "_blank", variant: "extern" },
  hochwasserschutzfibel: { href: "https://www.bmwsb.bund.de/SharedDocs/downloads/DE/publikationen/raumordnung/hochwasserschutzfibel.html", target: "_blank", variant: "extern" },
  bbkhochwasser: { href: "https://www.bbk.bund.de/DE/Themen/Risikomanagement/Baulicher-Bevoelkerungsschutz/Schutz-vor-Naturgefahren/Hochwasser/hochwasser_node.html", target: "_blank", variant: "extern" },
  bbsrstarkregen: { href: "https://www.bbsr.bund.de/BBSR/DE/veroeffentlichungen/sonderveroeffentlichungen/2018/leitfaden-starkregen-auflage-3-dl.pdf?__blob=publicationFile&v=2", target: "_blank", variant: "extern" },
  ubastarkregen: { href: "https://www.umweltbundesamt.de/publikationen/vorsorge-gegen-starkregenereignisse-massnahmen-zur", target: "_blank", variant: "extern" },
  bbkstarkregen: { href: "https://www.bbk.bund.de/SharedDocs/Downloads/DE/Mediathek/Publikationen/PiB/PiB-23-starkregen.pdf?__blob=publicationFile&v=8", target: "_blank", variant: "extern" },
  nrctaskforce: { href: "https://publishup.uni-potsdam.de/opus4-ubp/frontdoor/deliver/index/docId/50056/file/NRC_TaskForce.pdf", target: "_blank", variant: "extern" },
  grundwasserportal: { href: "https://www.berlin.de/sen/uvk/umwelt/wasser-und-geologie/grundwasser/informationen-zum-grundwasser/baugrund-und-grundwasserauskunft/", target: "_blank" },
  wassergeologie: { href: "https://www.berlin.de/sen/uvk/umwelt/wasser-und-geologie/", target: "_blank" },
} satisfies Record<string, { href: string; target?: string; variant?: string }>;