version: "3.8"

services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.28.x
    container_name: geoserver
    ports:
      - "8085:8080"
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_ADMIN_USER=admin
    volumes:
      - geoserver_data:/opt/geoserver_data
      - ./geoserver_logs:/opt/geoserver/logs
      - ./maps:/opt/geoserver_data/data/maps # Mount your maps directory

    restart: unless-stopped
    networks:
      - geoserver_network

volumes:
  geoserver_data:

networks:
  geoserver_network:
    driver: bridge
