export const technologiestiftungRules = {
	files: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"],
	languageOptions: {
		globals: {
			React: "readonly",
		},
	},
	rules: {
		"prefer-const": "error",
		"no-undef": "error",
		"no-var": "error",
		"default-case": ["error", { commentPattern: "^no default$" }],
		"arrow-parens": "error",
		"default-param-last": ["warn"],
		eqeqeq: "error",
		"max-depth": ["warn", 4],
		"max-params": ["warn", 3],
		complexity: ["warn", 10],
		"new-cap": [
			"error",
			{
				newIsCap: true,
				capIsNew: false,
				properties: false,
			},
		],
		"no-else-return": "error",
		"no-eval": "error",
		"no-implicit-globals": "error",
		"no-lonely-if": "error",
		"no-loop-func": "error",
		"no-multi-assign": "error",
		"no-multi-str": "error",
		"no-nested-ternary": "warn",
		"no-new": "error",
		"no-param-reassign": "error",
		"no-return-assign": "error",
		"no-shadow": "warn",
		"no-throw-literal": "error",
		"no-unneeded-ternary": "error",
	},
};
