[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/@sparticuz/chromium/bin/**",
    "node_modules/@sparticuz/chromium/lib/**",
    "node_modules/@sparticuz/chromium/chromium/**",
    "node_modules/@sparticuz/chromium/chromium-pack/**"
  ]