import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import "berlin-ui-library/dist/assets/style.css";
import React from "react";
import LayoutClient from "./LayoutClient";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();

	return (
		<html lang={locale}>
			<body className={`min-h-screen antialiased`}>
				<NextIntlClientProvider>
					<LayoutClient>{children}</LayoutClient>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
